(()=>{
'use strict';
const pages=[
['🌻 해바라기',`<path d="M245 290 V445 H265 V290Z"/><ellipse cx="210" cy="365" rx="48" ry="22"/><ellipse cx="300" cy="400" rx="48" ry="22"/>${Array.from({length:8},(_,i)=>`<ellipse cx="250" cy="133" rx="34" ry="65" transform="rotate(${i*45} 250 230)"/>`).join('')}<circle cx="250" cy="230" r="63"/>`],
['🦋 나비',`<ellipse cx="160" cy="190" rx="100" ry="115"/><ellipse cx="340" cy="190" rx="100" ry="115"/><ellipse cx="170" cy="350" rx="85" ry="95"/><ellipse cx="330" cy="350" rx="85" ry="95"/><circle cx="150" cy="190" r="40"/><circle cx="350" cy="190" r="40"/><ellipse cx="250" cy="280" rx="25" ry="145"/><circle cx="250" cy="125" r="32"/>`],
['🏡 우리 집',`<circle cx="410" cy="85" r="46"/><path d="M80 230H420V450H80Z"/><path d="M50 230L250 65L450 230Z"/><path d="M210 330H290V450H210Z"/><rect x="115" y="270" width="65" height="65"/><rect x="320" y="270" width="65" height="65"/>`],
['🐟 물고기',`<path d="M335 250L450 150V350Z"/><ellipse cx="220" cy="250" rx="150" ry="110"/><path d="M180 145L255 70L285 157Z"/><path d="M180 350L250 420L280 350Z"/><ellipse cx="130" cy="230" rx="24" ry="30"/><path d="M220 210L300 260L220 300Z"/>`],
['🌳 사과나무',`<path d="M220 270H280V455H220Z"/><path d="M120 320C20 270 60 180 100 170C80 70 190 40 240 90C310 20 420 90 400 170C475 230 430 340 350 325Z"/><circle cx="150" cy="200" r="28"/><circle cx="290" cy="140" r="28"/><circle cx="350" cy="255" r="28"/><circle cx="220" cy="280" r="28"/>`],
['⛵ 돛단배',`<path d="M65 355H440L370 445H140Z"/><path d="M240 65V325H75Z"/><path d="M265 95L430 325H265Z"/><circle cx="80" cy="80" r="43"/>`]
];
const colors=[['빨강','#e94b46'],['주황','#f89b35'],['노랑','#ffd95a'],['초록','#77b85a'],['파랑','#63a9e6'],['보라','#ab83d6'],['분홍','#f6a8c0'],['갈색','#ab7854'],['하양','#ffffff']];
document.addEventListener('DOMContentLoaded',()=>{
const hero=document.querySelector('.hero-classroom');if(!hero)return;const entry=document.createElement('section');entry.className='care-card solar-entry';entry.innerHTML='<div><h2>🎨 색칠공부방</h2><p>좋아하는 색으로 나만의 그림을 완성해요.</p></div><button class="care-btn primary" id="openColoringRoom" type="button">색칠공부방 들어가기</button>';hero.after(entry);
const room=document.createElement('dialog');room.id='coloringRoom';room.className='solar-room';room.setAttribute('aria-labelledby','coloringTitle');document.body.append(room);
let selected=0,color=colors[0][1];const paintings=pages.map(()=>({})),history=pages.map(()=>[]);const stop=()=>window.VoiceManager?.stopSpeaking();
function render(){room.innerHTML=`<div class="solar-header"><h2 id="coloringTitle">🎨 색칠공부방</h2><button type="button" data-coloring="close">◀ 방 나가기</button></div><p>① 도안 고르기 → ② 색 고르기 → ③ 그림의 원하는 부분 누르기</p><div class="coloring-templates">${pages.map((p,i)=>`<button type="button" data-template="${i}" aria-pressed="${selected===i}">${p[0]}</button>`).join('')}</div><div class="coloring-palette" aria-label="색 고르기">${colors.map(([name,hex])=>`<button type="button" data-color="${hex}" aria-pressed="${color===hex}"><span style="background:${hex}"></span>${name}</button>`).join('')}</div><p id="coloringStatus" role="status">선택한 색: ${colors.find(c=>c[1]===color)[0]}</p><svg id="coloringCanvas" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" aria-label="${pages[selected][0]} 색칠 도안">${pages[selected][1]}</svg><div class="solar-controls"><button type="button" data-coloring="undo" ${history[selected].length?'':'disabled'}>↶ 한 번 되돌리기</button><button type="button" data-coloring="clear">🧽 이 그림 지우기</button><button type="button" data-coloring="save">💾 그림 저장</button></div><p class="solar-note">정답은 없어요. 마음에 드는 색을 골라요. 도안을 바꿔도 이 창에서 칠한 색은 남아 있어요. 새로고침 전에 그림 저장을 눌러주세요.</p>`;
room.querySelectorAll('#coloringCanvas > *').forEach((el,i)=>{el.setAttribute('fill',paintings[selected][i]||'white');el.setAttribute('stroke','#423b34');el.setAttribute('stroke-width','5');el.setAttribute('stroke-linejoin','round');el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',`${i+1}번 부분 색칠하기`);const paint=()=>{history[selected].push({...paintings[selected]});paintings[selected][i]=color;el.setAttribute('fill',color);room.querySelector('[data-coloring="undo"]').disabled=false;room.querySelector('#coloringStatus').textContent=colors.find(c=>c[1]===color)[0]+'으로 색칠했어요.'};el.addEventListener('click',paint);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();paint()}})})}
room.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.template!==undefined){selected=Number(b.dataset.template);render();return}if(b.dataset.color){color=b.dataset.color;room.querySelectorAll('[data-color]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));room.querySelector('#coloringStatus').textContent='선택한 색: '+colors.find(c=>c[1]===color)[0];return}const a=b.dataset.coloring;if(a==='close')room.close();if(a==='undo'&&history[selected].length){paintings[selected]=history[selected].pop();render()}if(a==='clear'){history[selected].push({...paintings[selected]});paintings[selected]={};render()}if(a==='save'){const svg=room.querySelector('svg').cloneNode(true);svg.querySelectorAll('*').forEach(el=>{el.removeAttribute('tabindex');el.removeAttribute('role')});const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}));const link=document.createElement('a');link.href=url;link.download='색칠공부-'+selected+'.svg';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);room.querySelector('#coloringStatus').textContent='그림 다운로드를 요청했어요. 다운로드 폴더를 확인해주세요.'}});
entry.querySelector('button').onclick=()=>{stop();render();room.showModal()};room.addEventListener('close',stop);const sync=()=>entry.hidden=hero.hidden;sync();new MutationObserver(sync).observe(hero,{attributes:true,attributeFilter:['hidden']});
});
})();
