/* Consent rooms share elder IDs and remain part of the existing JSON backup. */
(()=>{'use strict';
const KEY='digital_school_management_v1',defs=window.CONSENT_FORMS,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let type='',elderId='',editing='',attachments=[];
window.ConsentRooms={open:(key,id)=>{if(defs.some(d=>d.key===key))room(key,id);}};
const load=()=>JSON.parse(localStorage.getItem(KEY)||'{"elders":[]}');
const def=()=>defs.find(d=>d.key===type),getElder=()=>load().elders.find(e=>e.elder_id===elderId);
const button=(label,action,id='')=>`<button type="button" class="care-btn" data-consent="${action}" data-id="${esc(id)}">${label}</button>`;
const input=(label,name,value='',required=false,kind='text')=>`<label class="care-field">${label}${required?' *':''}<input name="${name}" type="${kind}" value="${esc(value)}" ${required?'required':''}></label>`;
const area=(label,name,value='')=>`<label class="care-field">${label}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;
function choice(label,name,value=''){return `<fieldset class="care-choices"><legend>${label}</legend>${['동의','미동의'].map(v=>`<label><input type="radio" name="${name}" value="${v}" ${v===value?'checked':''} required>${v}</label>`).join('')}</fieldset>`;}
function show(title,html){const d=$('#careDialog');d.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" class="care-btn" data-action="close">✕ 닫기</button></header>${html}`;if(!d.open)d.showModal();}
function room(key,id){type=key;elderId=id??elderId;if(!load().elders.some(e=>e.elder_id===elderId))elderId='';const d=def(),e=getElder(),docs=(e?.consentDocuments||[]).filter(x=>x.type===type);show(d.title+' 방',`<p class="consent-room-note">기본 양식을 작성하고 서명한 서류를 이 방에 보관하세요. 서류 저장은 동의 상태를 자동 변경하지 않습니다.</p><label class="care-field">어르신<select id="consentPerson"><option value="">어르신을 선택해주세요</option>${load().elders.map(e=>`<option value="${esc(e.elder_id)}" ${e.elder_id===elderId?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label><div class="care-actions">${button('기본 양식 보기 · 인쇄','blank')}${button('새 동의서 작성','new')}<a class="care-btn" href="documents/${type}.html" download="${d.title}.html">빈 양식 다운로드</a></div><h3>이 방에 보관된 서류 ${docs.length}건</h3>${docs.map(r=>`<article class="consent-document-row"><b>${esc(r.date)} · ${esc(r.subject)}</b><p>${r.confirmed?'서명 원본 확인':'작성본 · 원본 확인 전'} · 첨부 ${r.attachments.length}개</p>${button('보기 · 인쇄','view',r.id)} ${button('수정 · 서류 첨부','edit',r.id)}</article>`).join('')||'<p>저장된 서류가 없습니다. 어르신을 선택하고 새 동의서를 작성해주세요.</p>'}`);}
function edit(id){if(!elderId){alert('먼저 어르신을 선택해주세요.');return;}const e=getElder(),d=def(),r=(e.consentDocuments||[]).find(x=>x.id===id)||{};editing=r.id||'';attachments=structuredClone(r.attachments||[]);show(d.title+' 작성',`<form id="consentForm" class="consent-editor"><p>기관의 실제 운영 기준을 확인하여 보유기간과 담당 연락처를 입력해주세요.</p><div class="consent-form-grid">${input('기관명','institution',r.institution,true)}${input('대상자 성명','subject',r.subject||e.name,true)}${input('동의 확인일','date',r.date||new Date().toLocaleDateString('en-CA'),true,'date')}${input('보유·이용기간 (기산점 포함)','retention',r.retention,true)}${input('철회·문의 담당자 및 연락처','contact',r.contact,true)}${input('설명한 담당자','worker',r.worker,true)}${input('동의자 성명','signer',r.signer,true)}${input('본인 / 대리인 및 대상자와의 관계','relation',r.relation||'본인',true)}</div>${area('수집·이용 목적','purpose',r.purpose||d.purpose)}${area('수집·이용 항목','items',r.items||d.items)}${area('안내 및 동의 내용','body',r.body||d.body)}${area('거부·철회 권리 및 영향','refusal',r.refusal||d.refusal)}${area('대리 동의 시 권한·위임 범위 확인 (해당 시)','authority',r.authority)}${type==='consent0'?`${choice('일반 개인정보 수집·이용','decision',r.decision)}${area('별도 민감정보 항목·목적·보유기간 (수집 시 작성)','sensitiveDetails',r.sensitiveDetails)}${choice('건강·인지상태 등 민감정보 별도 수집·이용','sensitive',r.sensitive)}`:choice(type==='consent3'?'사진 촬영':'위 내용에 대한 동의','decision',r.decision)}${type==='consent3'?`${choice('기관 내부 활동 기록 활용','internal',r.internal)}${choice('지정 보호자 보고서 활용','guardian',r.guardian)}${choice('외부 공개 게시 활용','public',r.public)}${input('공개 매체·게시 기간 (공개 동의 시 필수)','media',r.media)}`:''}${type==='consent1'?input('보호자 연락처','guardianPhone',r.guardianPhone||e.guardian):''}${type==='consent2'?`${input('참여 프로그램 / 장소','program',r.program,true)}${input('진행 기간','programPeriod',r.programPeriod,true)}${area('활동 지원·주의사항','support',r.support)}`:''}<p>성명 입력은 전자서명이 아닙니다. 출력 후 서명한 원본을 확인하여 첨부하거나 기관에서 별도 보관하세요.</p><label class="care-check"><input type="checkbox" name="confirmed" ${r.confirmed?'checked':''}> 서명된 원본을 담당자가 확인함</label>${input('원본 보관 위치 또는 확인 메모','originalLocation',r.originalLocation)}<h3>이 방에 서류 넣기</h3><label class="care-field">PDF / JPG / PNG (파일별 1MB 이하, 최대 3개)<input id="consentUpload" type="file" accept=".pdf,.png,.jpg,.jpeg" multiple></label><div id="consentFiles"></div><div class="care-actions"><button class="care-btn primary" type="submit">동의서 저장</button>${button('방으로 돌아가기','back')}</div></form>`);renderFiles();}
function renderFiles(){$('#consentFiles').innerHTML=attachments.map((a,i)=>`<div>${esc(a.name)} ${button('첨부 빼기','remove',i)}</div>`).join('');}
function paper(r){const d=def(),row=(label,value)=>`<dt>${label}</dt><dd>${esc(value)||'________________________________'}</dd>`;return `<article class="consent-paper"><h2>${esc(d.title)}</h2><dl>${row('기관명',r.institution)}${row('대상자',r.subject)}${row('확인일',r.date)}${row('보유·이용기간',r.retention)}${row('철회·문의',r.contact)}</dl><h3>1. 수집·이용 목적 및 항목</h3><p>${esc(r.purpose??d.purpose)}<br>${esc(r.items??d.items)}</p><h3>2. 안내 및 동의 내용</h3><p>${esc(r.body??d.body)}</p><h3>3. 거부·철회 권리</h3><p>${esc(r.refusal??d.refusal)}</p><h3>4. 동의 선택</h3><p>${type==='consent3'?'사진 촬영':'위 내용'}: ${esc(r.decision)||'□ 동의   □ 미동의'}</p>${type==='consent0'?`<p>민감정보 항목·목적·기간: ${esc(r.sensitiveDetails)||'________________________________'}</p><p>민감정보 별도 동의: ${esc(r.sensitive)||'□ 동의   □ 미동의'}</p>`:''}${type==='consent3'?`<p>기관 내부 기록: ${esc(r.internal)||'□ 동의   □ 미동의'}<br>지정 보호자 보고서: ${esc(r.guardian)||'□ 동의   □ 미동의'}<br>외부 공개 게시: ${esc(r.public)||'□ 동의   □ 미동의'}<br>공개 매체·게시기간: ${esc(r.media)||'________________________________'}</p>`:''}${type==='consent1'?`<p>보호자 연락처: ${esc(r.guardianPhone)||'________________________________'}</p>`:''}${type==='consent2'?`<p>참여 프로그램 / 장소: ${esc(r.program)||'________________________________'}<br>진행 기간: ${esc(r.programPeriod)||'________________________________'}<br>지원·주의사항: ${esc(r.support)||'________________________________'}</p>`:''}<h3>5. 설명 확인 및 서명</h3><p>위 내용을 설명받고 본인의 의사에 따라 선택하였습니다.</p><dl>${row('동의자 성명',r.signer)}${row('관계 / 자격',r.relation)}${row('대리 권한 확인',r.authority)}${row('설명 담당자',r.worker)}</dl><p class="signature-space">동의자 서명 또는 날인: ____________________</p><p class="signature-space">담당자 확인 서명: ____________________</p><p>원본 확인: ${r.confirmed?'확인함':'확인 전'} · ${esc(r.originalLocation)}</p></article>`;}
function preview(id){const r=(getElder()?.consentDocuments||[]).find(x=>x.id===id)||{};show(def().title,`<div class="care-actions no-print">${button('인쇄 / PDF 저장','print')}${button('방으로 돌아가기','back')}</div><div class="consent-preview">${paper(r)}</div><div class="no-print consent-file-list">${(r.attachments||[]).map((a,i)=>button('첨부 다운로드: '+esc(a.name),'download',r.id+':'+i)).join('')}</div>`);}
function inject(){const root=$('#careRoot');if(!root||root.querySelector('#consentRooms')||!root.querySelector('.consent-dashboard-room'))return;const node=document.createElement('section');node.id='consentRooms';node.className='care-card';node.innerHTML='<h2>동의서 보관함</h2><p>각 방에서 양식을 작성하고 서명한 서류를 보관하세요.</p><div class="consent-room-grid">'+defs.map(d=>button(d.icon+'<br>'+d.title,'room',d.key)).join('')+'</div>';root.querySelector('.consent-dashboard-room').after(node);}
document.addEventListener('DOMContentLoaded',()=>{if(!$('#careRoot'))return;new MutationObserver(inject).observe($('#careRoot'),{childList:true,subtree:true});inject();document.addEventListener('click',ev=>{const b=ev.target.closest('[data-consent]');if(!b)return;const id=b.dataset.id;switch(b.dataset.consent){case'room':room(id);break;case'new':edit();break;case'edit':edit(id);break;case'view':preview(id);break;case'blank':preview();break;case'back':room(type);break;case'print':window.print();break;case'remove':attachments.splice(Number(id),1);renderFiles();break;case'download':{const [docId,index]=id.split(':'),a=getElder().consentDocuments.find(x=>x.id===docId).attachments[Number(index)],link=document.createElement('a');link.href=a.data;link.download=a.name;link.click();break;}}});
document.addEventListener('change',async ev=>{if(ev.target.id==='consentPerson')room(type,ev.target.value);if(ev.target.id!=='consentUpload')return;const files=[...ev.target.files];if(files.length+attachments.length>3){alert('첨부는 최대 3개입니다.');return;}const next=[];try{for(const f of files){if(f.size>1048576||!['application/pdf','image/jpeg','image/png'].includes(f.type))throw Error('1MB 이하의 PDF, JPG, PNG만 첨부할 수 있습니다.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});next.push({name:f.name,mime:f.type,size:f.size,data});}attachments.push(...next);renderFiles();}catch(e){alert(e.message||'파일을 읽지 못했습니다.');}ev.target.value='';});
document.addEventListener('submit',ev=>{if(ev.target.id!=='consentForm')return;ev.preventDefault();const values=Object.fromEntries(new FormData(ev.target));if(values.sensitive==='동의'&&!values.sensitiveDetails.trim()){alert('민감정보 항목·목적·보유기간을 입력해주세요.');return;}if(values.public==='동의'&&!values.media.trim()){alert('공개 매체와 게시 기간을 입력해주세요.');return;}if(type==='consent3'&&values.decision==='미동의'&&['internal','guardian','public'].some(k=>values[k]==='동의')){alert('사진 촬영 미동의인 경우 활용 범위도 미동의로 선택해주세요.');return;}if(values.confirmed&&!values.originalLocation.trim()){alert('서명 원본 보관 위치 또는 확인 메모를 입력해주세요.');return;}try{const data=load(),e=data.elders.find(x=>x.elder_id===elderId);if(!e)throw Error('어르신을 찾을 수 없습니다.');e.consentDocuments ||= [];const r={...values,confirmed:!!values.confirmed,id:editing||crypto.randomUUID(),type,attachments:structuredClone(attachments),updatedAt:new Date().toISOString()},index=e.consentDocuments.findIndex(x=>x.id===r.id);if(index<0)e.consentDocuments.push(r);else e.consentDocuments[index]=r;localStorage.setItem(KEY,JSON.stringify(data));window.dispatchEvent(new StorageEvent('storage',{key:KEY}));room(type);}catch(e){alert('저장하지 못했습니다. 입력은 유지됩니다. 백업 후 저장 공간을 확인해주세요. '+e.message);}});
});
})();


