(()=>{'use strict';
 const $=id=>document.getElementById(id),date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
 const steps=[{id:'kongi',name:'콩이 운동',url:'senior-exercise.html'},{id:'tori',name:'토리 놀이',url:'tori-play.html'},{id:'nabi',name:'나비 학습',url:'nabi-learn.html'},{id:'bori',name:'보리 취미',url:'bori-hobby.html'}];
 const learner=RecordManager.getCurrentLearner(),key='digital_school_daily_course_v1:'+learner;
 let progress={date:date(),step:0,completed:[],seconds:[0,0,0,0],learner},frame=null,playing=false,loaded=false,last=0,observer=null;
 try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.date===date()&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<4&&Array.isArray(saved.seconds)&&saved.seconds.length===4){progress={...progress,...saved,seconds:saved.seconds.map(x=>Math.min(300,Math.max(0,Number(x)||0)))};progress.completed=steps.filter((_,i)=>progress.seconds[i]>=300).map(s=>s.id);}}catch{}
 function save(){progress.current=steps[progress.step].id;try{localStorage.setItem(key,JSON.stringify(progress));$('courseStorageStatus').textContent='';}catch{$('courseStorageStatus').textContent='진행 내용을 저장하지 못했어요. 선생님께 알려주세요.';}}
 function silence(){try{frame?.contentWindow.CharacterVoice?.stop();frame?.contentWindow.speechSynthesis?.cancel();const d=frame?.contentDocument;d?.querySelectorAll('audio,video').forEach(a=>a.pause());if(d?.querySelector('#btnPause')?.textContent.includes('멈춤'))d.querySelector('#btnPause').click();d?.querySelector('#btnLyricsStop')?.click();}catch{}window.speechSynthesis?.cancel();}
 function unload(){silence();observer?.disconnect();observer=null;frame?.remove();frame=null;loaded=false;}
 function clock(){const remaining=Math.ceil(300-progress.seconds[progress.step]);$('courseClock').textContent=remaining?'이번 활동 남은 시간 '+Math.floor(remaining/60)+'분 '+remaining%60+'초':'이번 5분 활동을 마쳤어요.';$('courseNext').disabled=remaining>0;$('coursePrevious').disabled=progress.step===0;$('coursePause').textContent=playing?'⏸ 쉬기':'▶ 이어서 하기';}
 function stageDone(){playing=false;silence();$('courseFrameHost').inert=true;progress.completed=steps.filter((_,i)=>progress.seconds[i]>=300).map(s=>s.id);$('courseMessage').textContent=progress.step<3?'다음은 '+steps[progress.step+1].name+'를 해볼까요?':'네 친구와 모두 함께했어요. 완료하기를 눌러주세요.';$('courseNext').textContent=progress.step===3?'활동 완료하기':'다음 활동 ▶';save();clock();}
 function load(){unload();$('courseStart').hidden=true;$('courseDone').hidden=true;$('coursePlaying').hidden=false;$('courseFrameHost').inert=false;$('courseStep').textContent=(progress.step+1)+' / 4 · '+steps[progress.step].name;$('courseMessage').textContent='편안한 만큼 참여해요. 쉬는 동안 시간은 멈춰요.';$('courseNext').textContent=progress.step===3?'활동 완료하기':'다음 활동 ▶';playing=false;clock();save();if(progress.seconds[progress.step]>=300){stageDone();return;}
 frame=document.createElement('iframe');frame.title=steps[progress.step].name+' 기존 활동';frame.src=steps[progress.step].url;
 frame.onload=()=>{if(!frame)return;const d=frame.contentDocument;if(!d?.body||!d.querySelector('#viewReady,.tp-game-menu,.nl-menu,.bh-menu')){$('courseMessage').textContent='활동을 불러오지 못했어요. 저장하고 나간 뒤 다시 시작해주세요.';return;}const style=d.createElement('style');style.textContent='header,.se-footer,.tp-footer,.nl-footer,.bh-footer{display:none!important}a[href*="index.html"],a[href*="character-house.html"],.room-flow-toolbar [data-room-back]{display:none!important}';d.head.append(style);const resize=()=>{if(frame)frame.style.height=Math.max(600,d.documentElement.scrollHeight)+'px';};observer=new ResizeObserver(resize);observer.observe(d.body);resize();loaded=true;playing=true;last=performance.now();clock();};$('courseFrameHost').append(frame);$('courseStep').focus();window.scrollTo(0,0);}
 function finish(){if(progress.completed.length!==4)return;unload();playing=false;try{const title='오늘의 20분 활동 · '+progress.date;const exists=RecordManager.getAllRecords().some(r=>r.learner===learner&&r.lessonTitle===title);if(!exists)RecordManager.saveRecord({learner,lessonTitle:title,lessonIcon:'🌼',isCompleted:true,durationText:'20분',assistanceNeeded:'네 캐릭터 활동에 참여함'});progress.recorded=true;}catch{$('courseStorageStatus').textContent='완료 기록 저장을 확인해주세요.';}save();$('coursePlaying').hidden=true;$('courseDone').hidden=false;}
 const continuing=progress.seconds.some(x=>x>0);$('resumeText').hidden=!continuing;$('courseRestart').hidden=!continuing;$('courseBegin').textContent=continuing?'이어서 하기':'시작하기';
 $('courseBegin').onclick=()=>progress.completed.length===4?finish():load();$('courseRestart').onclick=()=>{progress={date:date(),step:0,seconds:[0,0,0,0],completed:[],learner};load();};
 $('courseNext').onclick=()=>{if(progress.seconds[progress.step]<300)return;if(progress.step===3){finish();return;}progress.step++;load();};$('coursePrevious').onclick=()=>{if(progress.step>0){progress.step--;load();}};
 $('coursePause').onclick=()=>{if(!loaded||progress.seconds[progress.step]>=300)return;playing=!playing;last=performance.now();if(!playing)silence();$('courseFrameHost').inert=!playing;clock();save();};
 $('courseExit').onclick=()=>{playing=false;unload();save();location.href='index.html';};
 setInterval(()=>{const now=performance.now();if(playing&&loaded&&!document.hidden){progress.seconds[progress.step]=Math.min(300,progress.seconds[progress.step]+Math.min(1,(now-last)/1000));if(progress.seconds[progress.step]>=300)stageDone();clock();save();}last=now;},500);
 document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;silence();$('courseFrameHost').inert=true;save();clock();}});window.addEventListener('pagehide',()=>{playing=false;unload();save();});
})();
