/* Incremental room layers, bounded choices and theme defaults. */
(()=>{'use strict';
const palette=[['yellow','노랑','#eed486'],['pink','분홍','#e9bccb'],['purple','보라','#c4b1dc'],['blue','파랑','#b0cbdc'],['green','초록','#b7cba1'],['orange','주황','#e7bd94']];
const categories=[['furniture','가구'],['decor','소품'],['colors','색깔'],['room','벽/바닥'],['curtain','커튼'],['rug','러그'],['play','장난감'],['outfit','캐릭터 옷'],['accessories','액세서리'],['expression','표정'],['heldprops','손에 들기']];
const themes={kongi:{wallStyle:'w_cream',curtain:'yellow',rug:'yellow',special:'d_bone'},tori:{wallStyle:'w_pink',curtain:'pink',rug:'pink',special:'d_carrot'},nabi:{wallStyle:'w_purple',curtain:'purple',rug:'purple',special:'d_star'},bori:{wallStyle:'w_blue',curtain:'blue',rug:'blue',special:'t_tent'}};
const special=[{id:'t_slide',name:'작은 미끄럼틀',icon:'🛝'},{id:'t_tent',name:'아늑한 텐트',icon:'⛺'},{id:'t_box',name:'장난감 상자',icon:'🧺'},{id:'d_bone',name:'뼈다귀 쿠션',icon:'🦴'},{id:'d_carrot',name:'당근 소품',icon:'🥕'},{id:'d_star',name:'별 장식',icon:'⭐'},{id:'d_doghouse',name:'작은 강아지집',icon:'🏠'}];
const color=id=>palette.find(p=>p[0]===id)?.[2]||palette[0][2];
let page=0,lastKey='',surface='wall';
function button(text,fn){const b=document.createElement('button');b.type='button';b.className='cc-button';b.textContent=text;b.onclick=fn;return b;}
function setup(select,reset,back){const nav=document.querySelector('.ch-category-list');nav.replaceChildren();categories.forEach(([id,name])=>{const b=button(name,()=>select(id));b.classList.add('ch-cat-btn');b.dataset.cat=id;nav.append(b);});
const guide=document.createElement('nav');guide.id='roomEasyGuide';guide.setAttribute('aria-label','쉬운 꾸미기 순서');nav.parentElement.prepend(guide);
const summary=document.createElement('p');summary.id='roomSummary';document.querySelector('.ch-outfit-card').after(summary);
const status=document.createElement('p');status.id='roomSaveStatus';status.setAttribute('role','status');status.textContent='꾸민 뒤 저장하기를 눌러주세요.';document.querySelector('.ch-outfit-card').after(status);
const actions=document.createElement('div');actions.className='room-actions';actions.append(button('다른 방 고르기',back),button('기본 방으로 되돌리기',reset));document.querySelector('.ch-studio-grid').after(actions);
}
function guide(mode,cat,select){document.body.dataset.decorMode=mode;const el=document.getElementById('roomEasyGuide');el.replaceChildren();el.hidden=mode!=='easy';const i=Math.max(0,categories.findIndex(c=>c[0]===cat)),title=document.createElement('strong');title.textContent=`${categories[i][1]}을 골라볼까요?`;el.append(button('← 이전 주제',()=>select(categories[(i+categories.length-1)%categories.length][0])),title,button('다음 주제 →',()=>select(categories[(i+1)%categories.length][0])));document.getElementById('btnModeEasy').setAttribute('aria-pressed',String(mode==='easy'));document.getElementById('btnModeFree').setAttribute('aria-pressed',String(mode==='free'));document.getElementById('btnModeEasy').classList.toggle('active',mode==='easy');document.getElementById('btnModeFree').classList.toggle('active',mode!=='easy');}
function paginate(root,mode,key){root.querySelectorAll('.room-pagination').forEach(n=>n.remove());const choices=[...root.querySelectorAll('.ch-opt-card,.cc-choices>.cc-button')];const limit=mode==='easy'?4:6;if(key!==lastKey){page=0;lastKey=key;}page=Math.min(page,Math.max(0,Math.ceil(choices.length/limit)-1));const apply=()=>choices.forEach((el,i)=>el.hidden=Math.floor(i/limit)!==page);apply();if(choices.length<=limit)return;const nav=document.createElement('nav');nav.className='room-pagination';nav.setAttribute('aria-label','더 많은 선택지');const info=document.createElement('span');const update=()=>{apply();info.textContent=`${page+1} / ${Math.ceil(choices.length/limit)}`;};nav.append(button('← 앞의 것',()=>{page=(page+Math.ceil(choices.length/limit)-1)%Math.ceil(choices.length/limit);update();}),info,button('다른 것 보기 →',()=>{page=(page+1)%Math.ceil(choices.length/limit);update();}));root.append(nav);update();}
function paint(state){const scene=document.getElementById('roomViewport');scene.dataset.roomType=state.roomType;scene.dataset.roomId=state.currentCharId;scene.style.setProperty('--room-accent',color(state.curtain));
const win=document.getElementById('windowElem');win.innerHTML='<span aria-hidden="true" class="room-window-sky"></span><span class="room-curtain left"></span><span class="room-curtain right"></span>';win.setAttribute('aria-label',(palette.find(p=>p[0]===state.curtain)?.[1]||'노랑')+' 커튼');
const rug=document.getElementById('roomRug');rug.style.backgroundColor=color(state.rug);rug.style.backgroundImage='repeating-linear-gradient(0deg,transparent 0,transparent 5px,#ffffff35 6px,#ffffff35 8px)';rug.dataset.rug=state.rug;rug.style.borderRadius=state.rugShape==='round'?'50%':'18px';
const summary=document.getElementById('roomSummary');if(summary)summary.textContent=`가구·소품 ${state.placedItems.length}개 · ${palette.find(p=>p[0]===state.curtain)?.[1]||'노랑'} 커튼 · ${palette.find(p=>p[0]===state.rug)?.[1]||'노랑'} 러그`;
}
function simple(root,cat,state,change,wallStyles,floorStyles,roomTypes){let list,field;if(cat==='curtain'||cat==='rug'){field=cat;list=palette.map(([id,name,c])=>({id,name:name+(cat==='curtain'?' 커튼':' 러그'),color:c}));}else if(cat==='room'){const label=document.createElement('label');label.className='cc-part';label.textContent='꾸밀 곳';const select=document.createElement('select');select.setAttribute('aria-label','방에서 꾸밀 곳');[['wall','벽지'],['floor','바닥'],['structure','방 구조']].forEach(([v,t])=>select.add(new Option(t,v)));select.value=surface;select.onchange=()=>{surface=select.value;change(null,null);};label.append(select);root.append(label);field=surface==='wall'?'wallStyle':surface==='floor'?'floorStyle':'roomType';list=surface==='wall'?wallStyles:surface==='floor'?floorStyles:roomTypes;}else return false;
const grid=document.createElement('div');grid.className='cc-choices';root.append(grid);list.forEach(item=>{const b=button('',()=>change(field,item.id,item.name+'으로 바뀌었어요!'));b.classList.add('ch-opt-card');b.dataset.roomChoice=item.id;b.setAttribute('aria-label',item.name);b.setAttribute('aria-pressed',String(state[field]===item.id));b.innerHTML=(item.color?`<span class="cc-swatch" style="background:${item.color}"></span>`:`<span aria-hidden="true">${item.icon||'🏠'}</span>`)+`<span>${item.name}</span>`;grid.append(b);});if(cat==='rug')root.append(button(state.rugShape==='round'?'네모 러그로 바꾸기':'둥근 러그로 바꾸기',()=>change('rugShape',state.rugShape==='round'?'square':'round','러그 모양이 바뀌었어요!')));return true;}
window.RoomDecor={palette,categories,themes,special,setup,guide,paginate,paint,simple};
})();
