(()=>{
'use strict';
const cats=[['brain','🧠','두뇌교실','기억력·집중력 활동'],['talk','💬','말벗·회상교실','이야기하며 추억 떠올리기'],['heart','❤️','마음교실','마음과 감정 돌보기'],['health','🏃','건강교실','편안하게 따라 하는 활동'],['play','🎨','놀이교실','그림·음악·계절 놀이'],['ai','🤖','AI교실','AI와 재미있게 이야기하기']];
const items=[['brain','기억력 놀이','memory'],['brain','친구와 다양한 놀이','variety_play'],['brain','숫자 놀이 20단계','numbers'],['brain','단어 찾기','word_search'],['brain','가로세로 낱말','word_cross'],['brain','숫자 공부','@number'],['brain','생활 순서와 판단','daily'],['talk','사진 보며 이야기','photo'],['talk','이야기 여섯 편','@stories'],['talk','한글 공부','@hangul'],['talk','친구와 인사','greeting'],['heart','음악과 함께 쉬기','music'],['heart','고마운 마음 전하기','ai_writing'],['heart','추억 나누기','photo'],['health','관절운동 영상','@joint'],['health','생활 습관','school_habits'],['play','색칠공부','@coloring'],['play','나만의 취미','@hobby'],['play','그림 퍼즐','picture_puzzle'],['play','그림 빙고','picture_bingo'],['play','노래방','@karaoke'],['play','24절기 이야기','@solar'],['play','그림 만들기','art'],['ai','AI 알아보기','ai_basic'],['ai','내가 알고 싶은 것 질문하기','prompt_basic'],['ai','따뜻한 글쓰기','ai_writing'],['ai','그림 체험','ai_image'],['ai','생활 속 AI','ai_life'],['ai','재미있는 퀴즈','ai_quiz'],['ai','챗지피티 직접 질문','@chatgpt'],['ai','스마트폰 익히기','smartphone'],['ai','생활 질문','ask']];
items.push(['brain','물건 분류하기','school_sorting'],['brain','큰 숫자 찾기','school_larger'],['brain','시계 알아보기','school_clock'],['talk','속담 이어 말하기','school_proverbs'],['talk','초성으로 낱말 찾기','school_initials'],['play','명절 이야기','school_holidays'],['play','정다운 장보기','school_market']);
window.SchoolDifficulty={apply(id){const level=read('school_difficulty_'+personId(),'쉬움');if(['word_cross','word_search','picture_puzzle','picture_bingo'].includes(id)){LessonEngine.currentStepIndex={'쉬움':0,'보통':5,'도전':10}[level]||0;LessonEngine.renderCurrentStep();return level}return '콘텐츠 기본'}};
const links={'@number':'[data-study-open="number"]','@hangul':'[data-study-open="hangul"]','@stories':'.lesson-card[data-lesson-id="story"]','@joint':'#openJointRoom','@coloring':'#openColoringRoom','@hobby':'#openHobbyRoom','@karaoke':'#openKaraokeRoom','@solar':'#openSolarRoom','@chatgpt':'[data-open-chatgpt]'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const store=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{alert('저장하지 못했어요. 저장 공간을 확인해주세요.');return false}};
const btn=(text,action,value='')=>`<button type="button" data-school="${action}" data-value="${esc(value)}">${text}</button>`;
const personId=()=>localStorage.getItem('digital_school_active_elder_id')||'guest';
let categoryPage=0;
let page='home',mode='senior',running=null,lastId='greeting';
document.addEventListener('DOMContentLoaded',()=>{
const main=document.querySelector('main.main-wrapper');if(!main)return;
document.body.classList.add('school-redesign');document.body.dataset.schoolMode=mode;
const shell=document.createElement('div');shell.id='schoolShell';shell.innerHTML='<header class="school-header"><strong>🍊 디지털 AI 학교</strong><button type="button" id="schoolMenuToggle" aria-expanded="false" data-school="menu">☰ 학교 메뉴</button><nav id="schoolNav" aria-label="학교 메뉴"></nav><div class="school-tools">'+btn('🔊 화면 듣기','read')+btn('🐢 느리게 / 보통','speed')+btn('화면 모드 선택','mode')+'</div></header><main id="schoolPage"></main><section id="schoolStaff" hidden><div id="schoolStaffNav"></div><div id="schoolStaffMount"></div></section>';main.before(shell);document.querySelector('#schoolStaffMount').append(document.querySelector('#careRoot'));
const dialog=document.createElement('dialog');dialog.id='schoolDialog';dialog.className='solar-room';document.body.append(dialog);
function modal(title,body){dialog.innerHTML='<div class="solar-header"><h2>'+title+'</h2>'+btn('닫기','close')+'</div>'+body;if(!dialog.open)dialog.showModal()}
function go(target){window.VoiceManager.stopSpeaking();page=target;const staff=target==='staff'&&mode!=='senior';document.querySelector('#schoolStaff').hidden=!staff;document.querySelector('#schoolPage').hidden=staff;
document.querySelector('#schoolNav').innerHTML=[['home','학교 홈'],['today','오늘의 학교'],...cats.map(c=>[c[0],c[2]]),['history','나의 활동'],...(mode!=='senior'?[['staff','관리자센터']]:[])].map(([id,t])=>`<button type="button" data-school="nav" data-value="${id}" aria-current="${id===target?'page':'false'}">${t}</button>`).join('');
if(staff){document.querySelector('#schoolStaffNav').innerHTML='<h1>'+ (mode==='admin'?'관리자센터':'사회복지사·강사센터')+'</h1><p>이 기기의 자료를 관리합니다. 화면 모드는 계정 인증이 아닙니다.</p><div class="school-tools">'+[['home','대시보드'],['elders','대상자 관리'],['lessons','수업 시작'],['records','수업 기록'],['journals','프로그램 일지'],['analysis','활동 통계'],['reports','보호자 보고서'],...(mode==='admin'?[['admin','환경설정']]:[])].map(([id,t])=>btn(t,'care',id)).join('')+btn('놀이 시작 난이도','difficulty')+btn('콘텐츠 사용 설정','content')+btn('어르신 화면으로','logout')+'</div>';document.querySelector('.care-nav [data-value="home"]').click();return}
const el=document.querySelector('#schoolPage'),back=target==='home'?'':'<div class="school-tools">'+btn('← 이전으로','nav','home')+btn('🏠 처음으로','nav','home')+'</div>';
if(target==='home')el.innerHTML='<section class="school-welcome"><img src="assets/images/friend-kongi.png" alt="AI 친구 콩이"><div><h1>오늘도 즐겁게 함께해요.</h1><p>두뇌도 튼튼하게, 마음도 즐겁게.<br>나에게 맞는 활동을 시작해보세요.</p>'+btn('▶ 오늘의 수업 시작하기','daily')+'</div></section><div class="school-grid">'+cats.map(c=>btn(`<span>${c[1]}</span><strong>${c[2]}</strong><small>${c[3]}</small>`,'nav',c[0])).join('')+'</div>'+btn('🐶 함께할 친구 고르기','friends');
else if(target==='today')el.innerHTML=back+'<h1>오늘의 학교</h1><p>인사 → 날짜와 계절 → 몸풀기 → 두뇌활동 → 회상 → 놀이 → 마무리</p><p>한 단계씩 천천히 진행하고 마지막에 저장해요.</p>'+btn('▶ 오늘의 수업 시작하기','daily');
else if(target==='history'){const all=read('school_participation_v2',[]).filter(r=>r.personId===personId()),week=Date.now()-7*864e5;el.innerHTML=back+'<h1>나의 활동</h1><p>담당자가 선택한 대상자의 자유 활동 기록입니다. 대상자를 선택하지 않은 활동은 방문자 기록으로 표시됩니다.</p><p>최근 7일 동안 '+all.filter(r=>r.end>=week).length+'번 참여했어요.</p>'+all.slice().reverse().slice(0,20).map(r=>'<article class="care-card"><h2>'+esc(r.title)+'</h2><p>'+esc(r.date)+' · 완료했어요</p></article>').join('')+(all.length?'':'<p>아직 저장된 활동이 없어요.</p>');}
else{const c=cats.find(c=>c[0]===target);if(!c){go('home');return}const hidden=read('school_content_hidden',{});el.innerHTML=back+'<h1>'+c[1]+' '+c[2]+'</h1><p>'+c[3]+'</p>'+(target==='heart'?'<h2>오늘 기분이 어떠세요?</h2><div class="school-tools">'+['😊 좋아요','🙂 괜찮아요','😐 그냥 그래요','😔 속상해요'].map(t=>btn(t,'mood',t)).join('')+'</div><p id="schoolMood" role="status"></p>':'')+'<div class="school-grid">'+items.filter(a=>a[0]===target&&!hidden[a[2]]).slice(categoryPage*6,categoryPage*6+6).map(a=>btn('<strong>'+a[1]+'</strong><small>활동 시작 ▶</small>','activity',a[2])).join('')+'</div><div class="school-tools">'+(categoryPage>0?btn('◀ 앞 활동','activitypage',String(categoryPage-1)):'')+(items.filter(a=>a[0]===target&&!hidden[a[2]]).length>(categoryPage+1)*6?btn('다른 활동 더 보기 ▶','activitypage',String(categoryPage+1)):'')+'</div>'}window.scrollTo(0,0);
}
const start=LessonEngine.startLesson.bind(LessonEngine),finish=LessonEngine.finishLessonAndSave.bind(LessonEngine),exit=LessonEngine.exitLesson.bind(LessonEngine);
LessonEngine.startLesson=function(id){const l=window.LESSON_CATALOG.find(x=>x.id===id);if(mode==='senior'&&l){lastId=id;running={id,title:l.title,start:Date.now(),personId:personId(),category:items.find(a=>a[2]===id)?.[0]||'today'}}const result=start(id);if(mode==='senior')window.SchoolDifficulty.apply(id);return result};
LessonEngine.finishLessonAndSave=function(){if(mode!=='senior')return finish();if(running){const r={...running,end:Date.now(),date:new Date().toLocaleDateString('sv-SE')};if(!store('school_participation_v2',[...read('school_participation_v2',[]),r]))return;running=null}exit();modal('오늘도 정말 잘하셨어요.',btn('한 번 더 하기','again')+btn('다른 활동 하기','other')+btn('오늘 수업 끝내기','done'))};
function launch(id){lastId=id;if(id.startsWith('@'))document.querySelector(links[id])?.click();else LessonEngine.startLesson(id)}
function daily(){const now=new Date(),date=now.toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}),season=['겨울','겨울','봄','봄','봄','여름','여름','여름','가을','가을','가을','겨울'][now.getMonth()];const content=[['인사','오늘도 만나서 반가워요. 천천히 함께해요.'],['날짜와 계절',`오늘은 ${date}, ${season}이에요.`],['몸풀기','편히 앉아 손을 가볍게 펴고 오므려볼까요? 불편하면 쉬어도 괜찮아요.'],['두뇌활동','사과 두 개에 한 개를 더하면 세 개예요. 손가락으로 함께 세어볼까요?'],['회상','어릴 적 즐겨 먹던 음식은 무엇인가요? 편하게 이야기해주세요.'],['마음 표현 놀이','오늘을 색으로 표현한다면 어떤 색일까요? 좋아하는 색을 말해보세요.'],['마무리','함께해주셔서 고마워요. 오늘도 정말 잘하셨어요.']];const l={id:'school_daily',title:'오늘의 학교',icon:'🏫',steps:content.map(([t,s],i)=>({stepNum:i+1,screenText:`오늘 수업 ${i+1} / 7 · ${t}`,aiMessage:s,prompt:s,voiceScript:s,helpScript:'천천히 해도 괜찮아요.',options:[{text:'함께 참여했어요',emoji:'😊',isBest:true,feedback:'참 잘하셨어요.'},{text:'쉬면서 들었어요',emoji:'🌿',isBest:true,feedback:'편안하게 쉬어도 괜찮아요.'}]}))};l.steps[3].prompt='사과 두 개에 한 개를 더하면 몇 개일까요?';l.steps[3].options=[{text:'세 개',emoji:'🍎',isBest:true,feedback:'맞아요. 둘에 하나를 더하면 셋이에요.'},{text:'힌트를 듣고 다시 생각하기',emoji:'💡',isBest:false,feedback:'하나, 둘, 셋. 손가락을 세어보아요.'}];
const i=window.LESSON_CATALOG.findIndex(x=>x.id===l.id);if(i<0)window.LESSON_CATALOG.push(l);else window.LESSON_CATALOG[i]=l;launch(l.id)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-school]');if(!b)return;const a=b.dataset.school,v=b.dataset.value;if(a==='menu'){const nav=document.querySelector('#schoolNav');nav.classList.toggle('school-nav-open');b.setAttribute('aria-expanded',String(nav.classList.contains('school-nav-open')))}if(a==='nav'){categoryPage=0;go(v)}if(a==='activitypage'){categoryPage=Number(v);go(page)}if(a==='daily')daily();if(a==='activity')launch(v);if(a==='close')dialog.close();if(a==='read')VoiceManager.speak(document.querySelector('#schoolPage').innerText.slice(0,350));if(a==='speed')VoiceManager.toggleSpeed();
if(a==='mode')modal('화면 모드 선택','<p>계정 인증 서버가 연결되기 전에는 이 기기를 담당자와 함께 사용해주세요. 아래는 화면 구성 선택입니다.</p>'+btn('어르신','setmode','senior')+btn('사회복지사·강사','setmode','staff')+btn('기관 관리자','setmode','admin'));
if(a==='setmode'||a==='logout'){mode=a==='logout'?'senior':v;document.body.dataset.schoolMode=mode;dialog.close();go(mode==='senior'?'home':'staff')}
if(a==='care')document.querySelector(`.care-nav [data-value="${v}"]`)?.click();if(a==='mood'){document.querySelector('#schoolMood').textContent=v+'라고 느끼시는군요. 이야기해주셔서 고마워요.';VoiceManager.speak('이야기해주셔서 고마워요.')}
if(a==='again'){dialog.close();launch(lastId)}if(a==='other'||a==='done'){dialog.close();go(a==='done'?'history':'home')}
if(a==='friends'){const node=document.querySelector('.friend-selection');modal('함께할 친구 고르기','<div id="schoolFriendHost"></div>');const old=node.parentNode,next=node.nextSibling;dialog.querySelector('#schoolFriendHost').append(node);dialog.addEventListener('close',()=>old.insertBefore(node,next),{once:true})}
if(a==='difficulty')modal('놀이 시작 난이도','<p>현재 선택한 대상자의 퍼즐·빙고·낱말·단어찾기에 적용합니다. 다른 활동은 기존 단계 구성을 유지합니다.</p>'+['쉬움','보통','도전'].map(t=>btn(t,'setdifficulty',t)).join(''));if(a==='setdifficulty'){if(store('school_difficulty_'+personId(),v)){dialog.close()}}
if(a==='content'){const hidden=read('school_content_hidden',{});modal('콘텐츠 사용 설정','<p>이 기기의 교실 메뉴에 적용됩니다. 원본 수업은 삭제하지 않습니다.</p>'+items.filter((x,i,all)=>all.findIndex(a=>a[2]===x[2])===i).map(x=>`<label class="school-content-row"><input type="checkbox" data-content-id="${x[2]}" ${hidden[x[2]]?'':'checked'}> ${x[1]}</label>`).join(''))}
});dialog.addEventListener('change',e=>{if(e.target.dataset.contentId){const hidden=read('school_content_hidden',{});hidden[e.target.dataset.contentId]=!e.target.checked;store('school_content_hidden',hidden)}});go('home');
});
})();
