/* Local, non-personal guided activity drafts. Does not impersonate server content management. */
(()=>{'use strict';const key='school_guided_content_v1',C=window.SchoolServiceConfig;
 const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]').filter(x=>C[x.character]&&typeof x.title==='string'&&typeof x.prompt==='string');}catch{return [];}};
 window.ServiceContent={mountAdmin(host){if(sessionStorage.getItem('digital_school_teacher_authed')!=='true')return;const section=document.createElement('section');section.innerHTML='<h2>친구 집 안내 활동 편집</h2><p>이 기기의 콘텐츠 초안입니다. 다른 기기로 배포되지 않습니다. 개인정보가 없는 활동 안내만 입력해주세요.</p><p>이용 권한이 있거나 임베드가 허용된 콘텐츠만 등록해 주세요. 영상·음악은 영상·음악 콘텐츠 관리에서 등록해 주세요.</p><form><label>친구 집<select name="character"><option value="kongi">콩이집</option><option value="tori">토리집</option><option value="nabi">나비집</option><option value="bori">보리집</option></select></label><label>활동 이름<input name="title" maxlength="60" required></label><label>짧은 안내 또는 회상 질문<textarea name="prompt" maxlength="600" required></textarea></label><label>예상 시간(분)<input name="minutes" type="number" min="1" max="30" value="3" required></label><button type="submit">저장하기</button></form><p role="status"></p><div class="guided-content-list"></div>';host.append(section);let editing=null;const form=section.querySelector('form'),status=section.querySelector('[role=status]');function render(){const list=section.querySelector('.guided-content-list');list.replaceChildren();read().forEach(row=>{const p=document.createElement('p'),b=document.createElement('button');p.textContent=C[row.character].name+'집 · '+row.title+' ';b.type='button';b.textContent='수정';b.onclick=()=>{editing=row.id;for(const k of ['character','title','prompt','minutes'])form.elements[k].value=row[k];form.elements.title.focus();};p.append(b);list.append(p);});}form.onsubmit=e=>{e.preventDefault();if(sessionStorage.getItem('digital_school_teacher_authed')!=='true')return;const f=new FormData(form),minutes=Number(f.get('minutes'));if(!C[f.get('character')]||minutes<1||minutes>30)return;const row={id:editing||crypto.randomUUID(),character:f.get('character'),title:String(f.get('title')).trim().slice(0,60),prompt:String(f.get('prompt')).trim().slice(0,600),minutes};if(!row.title||!row.prompt)return;try{const rows=read(),index=rows.findIndex(x=>x.id===row.id);if(index<0)rows.push(row);else rows[index]=row;localStorage.setItem(key,JSON.stringify(rows));status.textContent='이 기기에 저장했어요.';editing=null;form.reset();render();}catch{status.textContent='저장 공간이 부족해 저장하지 못했어요.';}};render();}};
 document.addEventListener('DOMContentLoaded',()=>{if(window!==parent)return;const id=document.body.dataset.activityRoom||(document.getElementById('viewReady')?'kongi':null);if(!C[id])return;const rows=read().filter(x=>x.character===id);if(!rows.length)return;const host=document.querySelector('.tp-game-menu,.nl-menu,.bh-menu,#viewReady');if(!host)return;const details=document.createElement('details');details.className='service-guided';const summary=document.createElement('summary');summary.textContent='선생님이 준비한 활동';details.append(summary);host.after(details);const panel=document.createElement('section');panel.className='service-preparation service-guided-panel';panel.hidden=true;details.after(panel);
 function leave(){ServiceActivity.stop();panel.hidden=true;details.hidden=false;document.body.classList.remove('service-guided-running');summary.focus();}
 function start(row){panel.replaceChildren();panel.hidden=false;details.hidden=true;document.body.classList.add('service-guided-running');const h=document.createElement('h2'),p=document.createElement('p'),button=document.createElement('button'),back=document.createElement('button');h.textContent=row.title;p.textContent='약 '+row.minutes+'분 · 쉬움 · 준비가 되면 시작해요.';button.textContent='시작하기';back.textContent='다른 활동 고르기';back.onclick=leave;button.onclick=()=>{ServiceActivity.start(id,row.id,row.title);p.textContent=row.prompt;button.textContent='활동 마치기';button.onclick=()=>{h.textContent='정말 잘하셨어요!';ServiceActivity.complete(panel);button.textContent='한 번 더';button.onclick=()=>start(row);};};panel.append(h,p,button,back);h.tabIndex=-1;h.focus();}
 rows.forEach(row=>{const button=document.createElement('button');button.type='button';button.textContent=row.title+' · 약 '+row.minutes+'분';button.onclick=()=>start(row);details.append(button);});
 });
})();
