const{chromium}=require('playwright'),assert=require('assert/strict'),{wav}=require('../api/tts.js')._test;
const pcm=Buffer.alloc(24000*4*2);for(let i=0;i<24000*4;i++){const t=i/24000,amp=t<.45||(t>2&&t<2.4)?0:.32;pcm.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*220/24000)*amp*32767),i*2);}
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{
 const p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/api/tts',async r=>{await new Promise(ok=>setTimeout(ok,500));await r.fulfill({contentType:'audio/wav',body:wav(pcm)}).catch(()=>{});});
 await p.goto('http://localhost:8085/index.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>CharacterAnimation.expressionsReady);
 const blink=await p.evaluate(async()=>{const ids=['kongi','tori','nabi','bori'],events=[],last={},els=[...document.querySelectorAll('.home-friend .hanbok-character')];const box=()=>els.map(e=>{const r=e.querySelector('[data-part="fixed-body"]').getBoundingClientRect();const parent=e.getBoundingClientRect();return[r.x-parent.x,r.y-parent.y,r.width,r.height,getComputedStyle(e).transform];});const before=box(),start=performance.now();let overlap=0;
  const timer=setInterval(()=>{const now=performance.now();let n=0;for(const e of els){const on=e.classList.contains('is-blinking');if(on)n++;if(on!==!!last[e.dataset.character]){events.push({id:e.dataset.character,on,t:now-start});last[e.dataset.character]=on;}}overlap=Math.max(overlap,n);},10);await new Promise(r=>setTimeout(r,15500));clearInterval(timer);return{events,overlap,before,after:box(),animationCount:els.reduce((n,e)=>n+e.getAnimations({subtree:true}).length,0),fakeBow:ChuseokBow.play('kongi')};});
 assert.deepEqual(blink.before,blink.after);assert.equal(blink.animationCount,0);assert.equal(blink.overlap,1);assert.equal(blink.fakeBow,false);
 for(const id of ['kongi','tori','nabi','bori']){const events=blink.events.filter(e=>e.id===id),starts=events.filter(e=>e.on);assert(starts.length>=2,id);assert(starts[0].t>=900);for(let i=0;i<events.length-1;i++)if(events[i].on){const duration=events[i+1].t-events[i].t;assert(duration>=120&&duration<=190,id+' blink '+duration);}for(let i=1;i<starts.length;i++)assert(starts[i].t-starts[i-1].t>=3950&&starts[i].t-starts[i-1].t<=7400);}
 console.log('PASS static bodies, no bow/keyframes, staggered 150ms blink and 4–7s intervals');
 for(const id of ['kongi','tori','nabi','bori']){const r=await p.evaluate(async id=>{const seen=new Set(),others=[],silent=[],changes=[];let prev=null;const job=speakAsCharacter(id,'천천히 함께 이야기해요.');await new Promise(r=>setTimeout(r,150));const pending={mouth:CharacterAnimation.mouthStates[id],state:CharacterAnimation.state[id]};const timer=setInterval(()=>{const mouth=CharacterAnimation.mouthStates[id],level=CharacterVoice.getAudioLevel();if(mouth!==prev){changes.push({mouth,t:performance.now()});prev=mouth;}seen.add(mouth);if(level===0)silent.push(mouth);for(const [other,state]of Object.entries(CharacterAnimation.state))if(other!==id&&state!=='idle')others.push(other);},30);const result=await job;clearInterval(timer);return{seen:[...seen],others,silent,changes,pending,result,final:CharacterAnimation.mouthStates[id],state:CharacterAnimation.state[id]};},id);
  assert.equal(r.result.status,'ended');assert.deepEqual(r.pending,{mouth:'mouthSmile',state:'talking'});assert.deepEqual(new Set(r.seen),new Set(['mouthClosed','mouthA','mouthO','mouthE','mouthSmile']));assert.deepEqual(r.others,[]);assert(r.silent.filter(m=>m==='mouthClosed').length>r.silent.length*.6);assert.equal(r.final,'mouthSmile');assert.equal(r.state,'idle');console.log('PASS',id,'five textured mouths, independent audio, silence closes mouth, end returns idle');}
 const stop=await p.evaluate(async()=>{const first=speakAsCharacter('kongi','첫 인사');await new Promise(r=>setTimeout(r,750));const second=speakAsCharacter('tori','다음 인사');await new Promise(r=>setTimeout(r,750));CharacterVoice.stop();return{first:await first,second:await second,mouths:{...CharacterAnimation.mouthStates}};});assert.equal(stop.first.status,'cancelled');assert.equal(stop.second.status,'cancelled');assert(Object.values(stop.mouths).every(v=>v==='mouthSmile'));
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(400);assert.equal(await p.locator('.hanbok-character.is-blinking').count(),0);await p.evaluate(()=>speakAsCharacter('nabi','차분하게 함께해요.'));assert.equal(await p.getAttribute('.home-friend-nabi .hanbok-character','data-mouth'),'mouthSmile');
 for(const [width,height]of [[1920,1080],[1600,900],[1366,768],[768,1024],[390,844]]){await p.setViewportSize({width,height});assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1));}
 await p.emulateMedia({reducedMotion:'no-preference'});await p.unroute('**/api/tts');await p.route('**/api/tts',r=>r.fulfill({status:503,json:{error:'TTS_NOT_CONFIGURED',message:'test unavailable'}}));assert.equal((await p.evaluate(()=>speakAsCharacter('bori','연결 확인'))).status,'error');assert.equal(await p.evaluate(()=>CharacterAnimation.state.bori),'idle');assert.deepEqual(errors,[]);
 console.log('PASS cancellation, reduced motion, five viewports and failure recovery');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
