const {chromium}=require('playwright'),assert=require('node:assert/strict');
function wav(){const n=8000*4,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);return b;}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [390,768,1024,1440]){const context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage(),errors=[],requests=[];let enabled=false;const ids=['kongi','tori','nabi','bori'];const manifest=Object.fromEntries(ids.map(id=>[id,Object.fromEntries(['welcome','activity','goodjob'].map(s=>[s,`/public/audio/characters/${id}/${s}.wav`]))]));
await context.route('**/character-recordings.json',r=>r.fulfill({json:enabled?manifest:{}}));await context.route('**/public/audio/characters/**/*.wav',r=>{requests.push(r.request().url());return r.fulfill({contentType:'audio/wav',body:wav()})});
page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.testAudio=[];const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.testAudio.push(a);return a};window.spoken=0;speechSynthesis.speak=()=>window.spoken++;});await page.goto('http://127.0.0.1:8085/');await page.locator('#welcomeGreeting[open]').waitFor();await page.waitForTimeout(1000);
assert((await page.locator('.character-audio-controls:visible').count())>=1, 'Official greeting fallback remains available');assert.equal(requests.length,0);assert.equal(await page.locator('#welcomeGreeting img').count(),4);
enabled=true;await page.evaluate(()=>CharacterAudioPlayer.refresh());assert.equal(requests.length,0);
for(const id of ids){const figure=page.locator(`[data-welcome-friend="${id}"]`);await figure.locator('img').click({force:true});await page.waitForFunction(id=>CharacterAudioPlayer.getState().character===id&&CharacterAudioPlayer.getState().isPlaying,id);assert.equal(await page.evaluate(()=>testAudio.filter(a=>!a.paused).length),1);assert.equal(await page.locator('.character-audio-speaking').count(),1);assert.equal(await page.evaluate(()=>CharacterAudioPlayer.getState().volume),.7);await figure.getByRole('button',{name:'⏸ 잠시 멈춤',exact:true}).click({force:true});assert(!(await page.evaluate(()=>CharacterAudioPlayer.getState().isPlaying)));assert.equal(await page.locator('.character-audio-speaking').count(),0);await figure.getByRole('button',{name:'🔊 다시 듣기',exact:true}).click({force:true});await page.waitForFunction(()=>CharacterAudioPlayer.getState().isPlaying);assert((await page.evaluate(()=>CharacterAudioPlayer.getState().currentTime))<1);}
assert(await page.locator('#welcomeGreeting').evaluate(el=>el.scrollWidth<=el.clientWidth));await page.waitForFunction(()=>!CharacterAudioPlayer.getState().isPlaying);assert.equal(await page.locator('.character-audio-speaking').count(),0);
await page.locator('#welcomeStart').click();await page.locator('#morningProgram .character-audio-controls').getByRole('button',{name:'🔊 목소리 듣기',exact:true}).click();await page.waitForFunction(()=>CharacterAudioPlayer.getState().isPlaying);await page.locator('[data-morning="next"]').click();await page.waitForFunction(()=>!CharacterAudioPlayer.getState().isPlaying);await page.locator('[data-morning="next"]').click();await page.locator('#morningProgram .character-audio-controls').getByRole('button',{name:'🔊 목소리 듣기',exact:true}).click();await page.waitForFunction(()=>CharacterAudioPlayer.getState().situation==='activity'&&CharacterAudioPlayer.getState().character==='tori');await page.locator('[data-morning="home"]').first().click();
await page.locator('[data-senior-page="friends"]').first().click();await page.locator('[data-friend="kongi"]').click();await page.waitForFunction(()=>CharacterAudioPlayer.getState().character==='kongi'&&CharacterAudioPlayer.getState().isPlaying);await page.locator('[data-friend="tori"]').click();await page.waitForFunction(()=>CharacterAudioPlayer.getState().character==='tori'&&CharacterAudioPlayer.getState().isPlaying);assert.equal(await page.evaluate(()=>testAudio.filter(a=>!a.paused).length),1);assert.equal(await page.evaluate(()=>window.spoken),0);
await page.locator('#characterRoomsEntry').click();await page.locator('[data-character-room="nabi"]').click();await page.locator('#characterRooms .cw-character').click();await page.waitForFunction(()=>CharacterAudioPlayer.getState().character==='nabi'&&CharacterAudioPlayer.getState().isPlaying);assert.equal(await page.evaluate(()=>testAudio.filter(a=>!a.paused).length),1);assert(await page.locator('#characterRooms').evaluate(el=>el.scrollWidth<=el.clientWidth));enabled=false;await page.evaluate(()=>CharacterAudioPlayer.refresh());assert((await page.locator('.character-audio-controls:visible').count())>=1, 'Official greeting fallback remains available');assert(!(await page.evaluate(()=>CharacterAudioPlayer.getState().isPlaying)));assert.deepEqual(errors,[]);await context.close();console.log('PASS character audio at width '+width);}
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
