const{chromium}=require('playwright'),assert=require('assert/strict');(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.bows=[];document.addEventListener('animationstart',e=>{if(e.animationName.includes('waist-bow'))window.bows.push({id:e.target.closest('svg').dataset.character,time:performance.now()});});});await p.goto('http://localhost:8085/index.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('.is-bowing').length===4,{},{timeout:15000});await p.waitForFunction(()=>window.bows.length===4,{},{timeout:5000});const events=await p.evaluate(()=>window.bows);assert.equal(events.length,4);assert(Math.max(...events.map(e=>e.time))-Math.min(...events.map(e=>e.time))<50);
const lower=await p.locator('.hanbok-bow-lower').evaluateAll(es=>es.map(e=>({rect:{x:e.getBBox().x,y:e.getBBox().y,width:e.getBBox().width,height:e.getBBox().height},transform:getComputedStyle(e).transform})));
await p.evaluate(()=>document.querySelectorAll('.hanbok-bow-upper').forEach(el=>el.getAnimations({subtree:true}).forEach(a=>{a.pause();a.currentTime=1100;})));await p.locator('.home-friends-grid').screenshot({path:'tests/bow-waist-hold.png'});
assert.deepEqual(await p.locator('.hanbok-bow-lower').evaluateAll(es=>es.map(e=>({rect:{x:e.getBBox().x,y:e.getBBox().y,width:e.getBBox().width,height:e.getBBox().height},transform:getComputedStyle(e).transform}))),lower);
await p.evaluate(()=>document.querySelectorAll('.hanbok-bow-upper').forEach(el=>el.getAnimations({subtree:true}).forEach(a=>{a.pause();a.currentTime=1100;})));await p.waitForTimeout(50);const hold=await p.locator('.hanbok-bow-upper').evaluateAll(es=>es.map(e=>getComputedStyle(e).transform));await p.evaluate(()=>document.querySelectorAll('.hanbok-bow-upper').forEach(el=>el.getAnimations({subtree:true}).forEach(a=>a.currentTime=1300)));await p.waitForTimeout(50);assert.deepEqual(await p.locator('.hanbok-bow-upper').evaluateAll(es=>es.map(e=>getComputedStyle(e).transform)),hold);
await p.evaluate(()=>document.querySelectorAll('.hanbok-bow-upper').forEach(el=>el.getAnimations({subtree:true}).forEach(a=>a.finish())));await p.waitForTimeout(3000);assert.equal(await p.locator('.is-bowing').count(),0);assert.equal(await p.evaluate(()=>window.bows.length),4);
await p.emulateMedia({reducedMotion:'reduce'});await p.reload();await p.waitForTimeout(1200);assert.equal(await p.locator('.is-bowing').count(),0);for(const width of [768,390,320]){await p.setViewportSize({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}assert.deepEqual(errors,[]);await b.close();console.log('PASS simultaneous once-only greeting, fixed lower-body bounds, hold interval, no repeat, reduced motion and responsive');})();


