const assert=require('node:assert/strict'),G=require('../automation/garden');
const s={},g=G.init(s),start=Date.parse('2026-09-28T00:00:00Z');g.homes.a=G.home('a');g.homes.b=G.home('b');
G.act(s,'a',{action:'plant',plot:0,vegetable:'lettuce'},start);
assert.equal(G.stage(g.homes.a.plots[0],'real',start),0);
assert.equal(G.stage(g.homes.a.plots[0],'real',start+86400000),1);
assert.equal(G.stage(g.homes.a.plots[0],'real',start+3*86400000),3);
G.act(s,'a',{action:'water',plot:0},start);assert.throws(()=>G.act(s,'a',{action:'water',plot:0},start),/오늘/);
assert.throws(()=>G.act(s,'b',{action:'visit',target:'a'},start),/방문/);
g.homes.a.visitable=true;G.act(s,'b',{action:'help',target:'a',plot:0},start);assert.throws(()=>G.act(s,'b',{action:'help',target:'a',plot:0},start),/이미/);
for(const action of ['plant','harvest','water','care','delete','reset'])assert.throws(()=>G.act(s,'b',{action,target:'a',plot:0},start),/바꿀/);
assert.throws(()=>G.act(s,'b',{action:'greet',target:'a',text:'arbitrary script'},start),/골라/);
G.act(s,'b',{action:'greet',target:'a',text:G.greetings[0]},start);
G.act(s,'a',{action:'harvest',plot:0},start+3*86400000);assert.equal(g.homes.a.harvests.length,1);
g.homes.a.mode='lesson';G.act(s,'a',{action:'plant',plot:1,vegetable:'potato'},start);
G.act(s,'a',{action:'water',plot:1},start);G.act(s,'a',{action:'care',plot:1},start);
assert.equal(G.stage(g.homes.a.plots[1],'lesson',start+360000),3);
const restored=JSON.parse(JSON.stringify(s));assert.equal(G.view(restored.garden.homes.a,true,start+360000).plots[1].stage,3);
assert.deepEqual(Object.keys(G.view(g.homes.a,false)),['id','alias','own','mode','plots','basket']);
console.log('Garden rules: growth, persistence, limits, visitor permissions and projection passed');
