const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&/127\.0\.0\.1/.test(r.url()))errors.push(r.status()+' '+r.url())});
 await p.goto('http://127.0.0.1:8085/character-house.html');
 for(const [i,id] of ['kongi','tori','nabi','bori'].entries()){
  await p.locator('.ch-char-card').nth(i).click();assert.equal(await p.locator('#roomViewport').getAttribute('data-room-id'),id);
  const defaultWall=await p.locator('#roomWall').evaluate(e=>e.style.backgroundColor);assert.equal(defaultWall,['rgb(250, 246, 235)','rgb(253, 240, 244)','rgb(246, 240, 253)','rgb(240, 246, 253)'][i]);
  assert.equal(await p.locator('#optionsGrid [data-room-choice]:visible').count(),4);
  const before=await p.locator('#windowElem').screenshot();await p.getByRole('button',{name:'파랑 커튼',exact:true}).click();assert(!before.equals(await p.locator('#windowElem').screenshot())||id==='bori');
  await p.getByRole('button',{name:'다음 주제 →',exact:true}).click();await p.getByRole('button',{name:'분홍 러그',exact:true}).click();assert.equal(await p.locator('#roomRug').getAttribute('data-rug'),'pink');
  await p.locator('#btnModeFree').click();await p.locator('[data-cat=play]').click();assert.equal(await p.locator('#optionsGrid .ch-opt-card:visible').count(),6);
  const count=await p.locator('#itemsLayer .ch-placed-item').count();await p.getByRole('button',{name:'작은 미끄럼틀 방에 놓기',exact:true}).click();assert.equal(await p.locator('#itemsLayer .ch-placed-item').count(),count+1);assert.equal(await p.locator('[data-item-id=t_slide] svg').count(),1);
  await p.locator('#btnPlaceRight').click();await p.locator('#btnBottomSave').click();const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('senior_character_house_data_v1')));assert.equal(saved.rooms[id].curtain,'blue');assert.equal(saved.rooms[id].rug,'pink');assert(saved.rooms[id].placedItems.some(i=>i.id==='t_slide'));
  await p.getByRole('button',{name:'다른 방 고르기',exact:true}).click();
 }
 await p.reload();assert.match(await p.locator('#stageTitle').innerText(),/보리/);assert.equal(await p.locator('[data-item-id=t_slide]').count(),1);
 await p.getByRole('button',{name:'기본 방으로 되돌리기',exact:true}).click();assert.equal(await p.locator('[data-item-id=t_slide]').count(),0);assert.equal(await p.locator('#roomRug').getAttribute('data-rug'),'blue');await p.locator('#btnBottomUndo').click();assert.equal(await p.locator('[data-item-id=t_slide]').count(),1);assert.equal(await p.locator('#roomRug').getAttribute('data-rug'),'pink');
 await p.getByRole('button',{name:'다른 방 고르기',exact:true}).click();await p.locator('.ch-char-card').first().click();assert.equal(await p.locator('[data-item-id=t_slide]').count(),1);await p.locator('#btnModeFree').click();await p.locator('[data-cat=outfit]').click();await p.locator('[data-choice=knit]').click();assert.equal(await p.locator('[data-layer=outfit]').count(),1);await p.locator('#btnModeEasy').click();await p.getByRole('button',{name:'다음 주제 →',exact:true}).click();assert.equal(await p.locator('#optionsGrid [data-room-choice]:visible').count(),4);
 assert.deepEqual(errors,[]);console.log('PASS 4 independent rooms, themes, live curtains/rugs/furniture, modes, auto restore, reset/undo and customization');await p.close();
 for(const width of [1024,768,390]){const q=await b.newPage({viewport:{width,height:950}});await q.goto('http://127.0.0.1:8085/character-house.html');await q.locator('.ch-char-card').first().click();assert(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await q.locator('#btnModeFree').click();await q.locator('[data-cat=outfit]').click();await q.locator('[data-choice=knit]').click();assert(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await q.screenshot({path:'tests/rooms-'+width+'.png',fullPage:true});await q.close();console.log('PASS room responsive '+width);}
 const old=await b.newPage();await old.addInitScript(()=>localStorage.setItem('senior_character_house_data_v1',JSON.stringify({currentCharId:'nabi',roomType:'room_window',wallStyle:'w_purple',floorStyle:'f_wood_warm',placedItems:[{id:'f_sofa',uid:'legacy-sofa',name:'폭신한 소파',icon:'🛋️',x:20,y:70,scale:1,rot:0}],outfit:{top:'top_knit'}})));await old.goto('http://127.0.0.1:8085/character-house.html');assert.equal(await old.locator('[data-uid=legacy-sofa]').count(),1);await old.locator('#btnBottomSave').click();const migrated=await old.evaluate(()=>JSON.parse(localStorage.getItem('senior_character_house_data_v1')));assert.equal(migrated.rooms.nabi.placedItems[0].uid,'legacy-sofa');assert.equal(migrated.outfit.top,'top_knit');console.log('PASS legacy data migration without lost furniture');await old.close();
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
